// <auto-generated />
using System;
using LsiTestWebAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LsiTestWebAPI.Migrations
{
    [DbContext(typeof(LSIDbContext))]
    partial class LSIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LsiTestWebAPI.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfRaport")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfRaport = new DateTime(2021, 8, 3, 14, 20, 13, 501, DateTimeKind.Local).AddTicks(4799),
                            LocalName = "Lokal 1",
                            Name = "Raport 1",
                            UserName = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            DateOfRaport = new DateTime(2021, 8, 3, 14, 20, 13, 506, DateTimeKind.Local).AddTicks(4211),
                            LocalName = "Lokal 1",
                            Name = "Raport 1",
                            UserName = "User 1"
                        },
                        new
                        {
                            Id = 3,
                            DateOfRaport = new DateTime(2021, 8, 3, 14, 20, 13, 506, DateTimeKind.Local).AddTicks(4325),
                            LocalName = "Lokal 1",
                            Name = "Raport 1",
                            UserName = "User 1"
                        },
                        new
                        {
                            Id = 4,
                            DateOfRaport = new DateTime(2021, 8, 3, 14, 20, 13, 506, DateTimeKind.Local).AddTicks(4338),
                            LocalName = "Lokal 1",
                            Name = "Raport 1",
                            UserName = "User 1"
                        },
                        new
                        {
                            Id = 5,
                            DateOfRaport = new DateTime(2021, 8, 3, 14, 20, 13, 506, DateTimeKind.Local).AddTicks(4346),
                            LocalName = "Lokal 1",
                            Name = "Raport 1",
                            UserName = "User 1"
                        },
                        new
                        {
                            Id = 6,
                            DateOfRaport = new DateTime(2021, 8, 3, 14, 20, 13, 506, DateTimeKind.Local).AddTicks(4355),
                            LocalName = "Lokal 1",
                            Name = "Raport 1",
                            UserName = "User 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
